### ISSUE TITLE
奇怪的报错

### ISSUE THREAD

**Issue by Polaris-FromAs** [HunterShenSmzh/Translate-script-based-on-MTool-and-Text-Generation-webui#1]
![image](https://github.com/HunterShenSmzh/Translate-script-based-on-MTool-and-Text-Generation-webui/assets/172151744/51e44cc1-e6fb-4adc-97f2-b6023a5c01ef)

**Comment by Polaris-FromAs** [comment]
![image](https://github.com/HunterShenSmzh/Translate-script-based-on-MTool-and-Text-Generation-webui/assets/172151744/279f2206-3f6d-44eb-a6ab-427d1628a38d)
看netstat更改了端口后，又变了

**Comment by HunterShenSmzh** [comment]
tgw的api端口是默认5000的，建议检查api是否正常启动
